import { StyleSheet, Dimensions } from 'react-native';

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  signupText: {
    fontSize: 18,
    lineHeight: 24,
    marginTop: 16,
    textAlign: 'center',
    color: '#2C84FC',
    fontWeight: '700',
  },
  emptyView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  label: {
    fontSize: 14,
    lineHeight: 14,
    color: '#2A2A2A',
    textAlign: 'center',
  },
  header: {
    height: 40,
    paddingTop: 16,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  logoutView: {
    top: 16,
    right: 24,
    position: 'absolute',
  },
  headerText: {
    fontSize: 16,
    lineHeight: 19,
    color: '#2A2A2A',
    fontWeight: '700',
    textAlign: 'center',
  },
  flatListStyles: {
    marginTop: 16,
  },
  button: {
    height: 58,
    width: 58,
    bottom: 40,
    right: 24,
    zIndex: 1,
    borderRadius: 58 / 2,
    alignItems: 'center',
    position: 'absolute',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 8,
    backgroundColor: '#2C84FC',
  },
  label: {
    fontSize: 14,
    lineHeight: 14,
    color: '#2A2A2A',
    textAlign: 'left',
  },
  eachContainer: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  textInput: {
    height: 40,
    fontSize: 14,
    width: '100%',
    paddingVertical: 0,
    padding: 0,
    lineHeight: 14,
    textAlign: 'left',
    borderRadius: 6,
    paddingLeft: 8,
    paddingRight: 50,
    color: '#2A2A2A',
  },
  modalView: {
    flex: 1,
    justifyContent: 'center',
  },
  overlay: {
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    opacity: 0.4,
    position: 'absolute',
    backgroundColor: '#000',
  },
  roomNameInputWrapper: {
    borderRadius: 9,
    marginHorizontal: 32,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 8,
    backgroundColor: '#FFF',
    justifyContent: 'center',
  },
});
